# fly.toml app configuration file generated for juanse-test on 2023-08-21T15:44:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "juanse-test"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[build]

[deploy]

[processes]
  app = "/bin/sh -c './bin/rails db:prepare && ./bin/rails db:migrate && ./bin/rails server'"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
